APP_NAME: "sample"
APP_PORT: 8080
SENTRY_ENABLED: true
LOG_LEVEL: "info"
DB_HOST: "localhost"
DB_USER: "test"
DB_PASSWORD: "12345"
DB_NAME: "test"
DB_PORT: 5432
DB_MAX_IDLE_CONNECTION: 10
DB_MAX_POOL_SIZE: 10
